language:
- python
python:
- '3.4'
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: ZSolAYq929hOQ93fe4eyCjUTk+VafYXpkNvnP4hNyH6Qt3iejqTBxKhTUhQ5jvQgV3pFzhwFRk8hv+LwlJqy/WliAm+DbsbjLS0LzoRmKP9fAvieVoUzXnWvt5ujqEH/CjOwxn21v2VPbwyIvCUlOCECcupmaOt+fXGRKObu4ORCkP/n1pyXalffsq7e4zrCh4YnCesLZMLT6DmR1sMAXNTNdlUHN1BoVk+SCEqiFMdVmRElZ+kFAo5vi4d2HABIkDWzJO79dWgFCwNWS4c6eE5/lM+zL3ogHH+o/y6O16dqKE8z81davQqQFkLjelT4AJvj0u97kCYzmiJRkF7CALcW/02ropRhNKY14kPBkZizB2MMc8KIjFVQbq6u40Nioxu2eV28AK+QkfcwuS0TV0DxubGbDtnT69FT1I0tMpkBMCamrp8eADxye0lERUi6eB1BL/qinDrHpyU56bluW1U+sNbyk9tb7o1LxqQZECeosRbFm4Z4/UCpiG/jjjgPzteSCIH0mHxY6lK+l3VaUsilUh4Iv26KyAMnefSfzMSq7JVnpc7TqXqOsewbtaszH+LwBfOzBF0eU47aH63h2gAF3yKTJhCc5cdjUNHpfLeGEt9dvF2bg8fraIflKFJjcWur0TZqmVMyJjfiY7YEhxP/lJ8SMZbVdewEco3TBf8=
  app: stamates-flasktaskr
  on:
    branch: master
    python: '3.4'
    repo: Stamates/flasktaskr_heroku
