language:
- python
python:
- '3.4'
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: eUEUJ0/BR/2DYQTPxjE22c/RODtnTxvnNOfHweM8gI1toCGWVdt3wRcxgFyNLUuiI2NaDl+GO9q3FkMyVPlmBeCJE3kkZ3a7KcL3V+qOBBJ0A6WIdC4CiVKBRb2GtKneOLOCqJEQvGBsmy5eu0EWSq7wEZbMi1l2/FnFtM7VXmzksD9GRupfq/JyMIbNNkQiQyxIs1nNPAwvDFJ/tJQH16R0PsTd8J8wWfc6W8mLtYPoEeptBZ5suBlU8nMpPAXequQVXw0+xaKQ9ypXnNOny0lJh/rsM0vqSra3hm5rqEJPE+AMnkn8iII5rB7GSAB+LOlOS1FRGbuivOqXxcAREjWS1rsAWVwxdVG92fY+xzlEMniNm7q/DU5A0LcOioiP9x7VRDoKzvUso85AJkTMeg/44TCSLiSCRQQAaLFjBJGHTBn4pvPeUrIwnqLN9HbLMGREckRoBUGT0+RcaXQxc+9IGt8gLZEQdbljUjxwHhwa/IZjmfb6nxFTS3Bl9EsHTfLUOlFdHLHBufHc35Zh7X9jB78c3HYzYzqXGVa4JaUSrRM2qhNvm6ahqR03ToemtE62dKKbu9qdiyvWPKUbm8SEf7DaeQW0Qowe8TQ//KKBkpM/g/ZQIUsyaqfPcBv/GFBhhuUVRU+/kwF7ug1oR0yPfMV8qoL771FDrX99aro=
  app: stamates-flasktaskr
  on:
    branch: master
    python: '3.4'
    repo: Stamates/flasktaskr_heroku
